- name: make sure nodejs is installed
  become: yes
  apt: 
    name:         nodejs 
    state:        present

- name: make nodejs available as node command
  become: yes
  file: 
    src:    /usr/bin/nodejs
    dest:   /usr/bin/node
    state:  link

- name: make sure npm is installed
  become: yes
  apt: 
    name:         npm 
    state:        present

